/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SermonsRouteImport } from './routes/sermons'
import { Route as MinistriesRouteImport } from './routes/ministries'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BulletinRouteImport } from './routes/bulletin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinistriesMinistryIdRouteImport } from './routes/ministries_.$ministryId'
import { Route as EventsEventIdRouteImport } from './routes/events_.$eventId'

const SermonsRoute = SermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesRoute = MinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BulletinRoute = BulletinRouteImport.update({
  id: '/bulletin',
  path: '/bulletin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesMinistryIdRoute = MinistriesMinistryIdRouteImport.update({
  id: '/ministries_/$ministryId',
  path: '/ministries/$ministryId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events_/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bulletin': typeof BulletinRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/ministries': typeof MinistriesRoute
  '/sermons': typeof SermonsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/ministries/$ministryId': typeof MinistriesMinistryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bulletin': typeof BulletinRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/ministries': typeof MinistriesRoute
  '/sermons': typeof SermonsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/ministries/$ministryId': typeof MinistriesMinistryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bulletin': typeof BulletinRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/ministries': typeof MinistriesRoute
  '/sermons': typeof SermonsRoute
  '/events_/$eventId': typeof EventsEventIdRoute
  '/ministries_/$ministryId': typeof MinistriesMinistryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bulletin'
    | '/contact'
    | '/events'
    | '/ministries'
    | '/sermons'
    | '/events/$eventId'
    | '/ministries/$ministryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bulletin'
    | '/contact'
    | '/events'
    | '/ministries'
    | '/sermons'
    | '/events/$eventId'
    | '/ministries/$ministryId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bulletin'
    | '/contact'
    | '/events'
    | '/ministries'
    | '/sermons'
    | '/events_/$eventId'
    | '/ministries_/$ministryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BulletinRoute: typeof BulletinRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  MinistriesRoute: typeof MinistriesRoute
  SermonsRoute: typeof SermonsRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  MinistriesMinistryIdRoute: typeof MinistriesMinistryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sermons': {
      id: '/sermons'
      path: '/sermons'
      fullPath: '/sermons'
      preLoaderRoute: typeof SermonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries': {
      id: '/ministries'
      path: '/ministries'
      fullPath: '/ministries'
      preLoaderRoute: typeof MinistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulletin': {
      id: '/bulletin'
      path: '/bulletin'
      fullPath: '/bulletin'
      preLoaderRoute: typeof BulletinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries_/$ministryId': {
      id: '/ministries_/$ministryId'
      path: '/ministries/$ministryId'
      fullPath: '/ministries/$ministryId'
      preLoaderRoute: typeof MinistriesMinistryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$eventId': {
      id: '/events_/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BulletinRoute: BulletinRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  MinistriesRoute: MinistriesRoute,
  SermonsRoute: SermonsRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  MinistriesMinistryIdRoute: MinistriesMinistryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
